
using Godot;
using System.Collections.Generic;

namespace Overlay.Core.Services.ColorInterpolators;

public sealed class ServiceColorInterpolatorNormalDefinition : IServiceColorInterpolatorDefinition
{
    public static Dictionary<IServiceColorInterpolatorDefinition.ColorType, Color> ColorCodes { get; } = new()
    {
        { IServiceColorInterpolatorDefinition.ColorType.Red,                         new Color(rgba: 0xFF0000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Yellow,                      new Color(rgba: 0xFFFF00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Green,                       new Color(rgba: 0x00FF00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyan,                        new Color(rgba: 0x00FFFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Blue,                        new Color(rgba: 0x0000FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Magenta,                     new Color(rgba: 0xFF00FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Orange,                      new Color(rgba: 0xFF8F00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Purple,                      new Color(rgba: 0x9C27B0FF) },
        { IServiceColorInterpolatorDefinition.ColorType.White,                       new Color(rgba: 0xF2F2F2FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.BananaShake0,                new Color(rgba: 0xF9A825FF) },
        { IServiceColorInterpolatorDefinition.ColorType.BananaShake1,                new Color(rgba: 0xFBC02DFF) },
        { IServiceColorInterpolatorDefinition.ColorType.BananaShake2,                new Color(rgba: 0xFDD835FF) },
        { IServiceColorInterpolatorDefinition.ColorType.BananaShake3,                new Color(rgba: 0xFFF176FF) },
        { IServiceColorInterpolatorDefinition.ColorType.BananaShake4,                new Color(rgba: 0xFFF9C4FF) },
        { IServiceColorInterpolatorDefinition.ColorType.BananaShake5,                new Color(rgba: 0xFFFDE7FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Blue0,                       new Color(rgba: 0x1A237EFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Blue1,                       new Color(rgba: 0x283593FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Blue2,                       new Color(rgba: 0x303F9FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Blue3,                       new Color(rgba: 0x3949ABFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Blue4,                       new Color(rgba: 0x3F51B5FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Blue5,                       new Color(rgba: 0x5C6BC0FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.BlueRaspberry0,              new Color(rgba: 0x0000FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.BlueRaspberry1,              new Color(rgba: 0x0040FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.BlueRaspberry2,              new Color(rgba: 0x0080FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.BlueRaspberry3,              new Color(rgba: 0x00BFFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.BlueRaspberry4,              new Color(rgba: 0x00FFFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.BlueRaspberry5,              new Color(rgba: 0x80FFFFFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Border0,                     new Color(rgba: 0xEEEEEEFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Border1,                     new Color(rgba: 0xBDBDBDFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Border2,                     new Color(rgba: 0x9E9E9EFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Border3,                     new Color(rgba: 0x757575FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Border4,                     new Color(rgba: 0x424242FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Border5,                     new Color(rgba: 0x212121FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBanana0,           new Color(rgba: 0xFFD700FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBanana1,           new Color(rgba: 0xFFE135FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBanana2,           new Color(rgba: 0xFFEC8BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBanana3,           new Color(rgba: 0xFFF4AFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBanana4,           new Color(rgba: 0xFFF9C4FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBanana5,           new Color(rgba: 0xFFFDE7FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBlueberry0,        new Color(rgba: 0x3F51B5FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBlueberry1,        new Color(rgba: 0x4F86F7FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBlueberry2,        new Color(rgba: 0x7A9EFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBlueberry3,        new Color(rgba: 0xADCFFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBlueberry4,        new Color(rgba: 0xD0E1FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleBlueberry5,        new Color(rgba: 0xE8F0FFFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleDragonfruit0,      new Color(rgba: 0xC2185BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleDragonfruit1,      new Color(rgba: 0xE91E63FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleDragonfruit2,      new Color(rgba: 0xF06292FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleDragonfruit3,      new Color(rgba: 0xF48FB1FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleDragonfruit4,      new Color(rgba: 0xF8BBD0FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleDragonfruit5,      new Color(rgba: 0xFFE4EFFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleLime0,             new Color(rgba: 0x388E3CFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleLime1,             new Color(rgba: 0x4CAF50FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleLime2,             new Color(rgba: 0x81C784FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleLime3,             new Color(rgba: 0xA5D6A7FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleLime4,             new Color(rgba: 0xC8E6C9FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleLime5,             new Color(rgba: 0xE8F5E9FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleOrange0,           new Color(rgba: 0xE65100FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleOrange1,           new Color(rgba: 0xFF8C00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleOrange2,           new Color(rgba: 0xFFA726FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleOrange3,           new Color(rgba: 0xFFCC80FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleOrange4,           new Color(rgba: 0xFFE0B2FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleOrange5,           new Color(rgba: 0xFFF3E0FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleStrawberry0,       new Color(rgba: 0xD32F2FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleStrawberry1,       new Color(rgba: 0xF44336FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleStrawberry2,       new Color(rgba: 0xFF8A80FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleStrawberry3,       new Color(rgba: 0xFFAB91FF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleStrawberry4,       new Color(rgba: 0xFFCCBCFF) },
        { IServiceColorInterpolatorDefinition.ColorType.CreamsicleStrawberry5,       new Color(rgba: 0xFFEBE6FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Cyan0,                       new Color(rgba: 0x004D40FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyan1,                       new Color(rgba: 0x00695CFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyan2,                       new Color(rgba: 0x00796BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyan3,                       new Color(rgba: 0x00897BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyan4,                       new Color(rgba: 0x009688FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyan5,                       new Color(rgba: 0x4DB6ACFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Cyberpunk0,                  new Color(rgba: 0x00E5FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyberpunk1,                  new Color(rgba: 0x18FFFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyberpunk2,                  new Color(rgba: 0x448AFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyberpunk3,                  new Color(rgba: 0x7C4DFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyberpunk4,                  new Color(rgba: 0xD500F9FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Cyberpunk5,                  new Color(rgba: 0xFF00FFFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Dinner0,                     new Color(rgba: 0x3E2723FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Dinner1,                     new Color(rgba: 0x5D4037FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Dinner2,                     new Color(rgba: 0x8D6E63FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Dinner3,                     new Color(rgba: 0xA1887FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Dinner4,                     new Color(rgba: 0xD7CCC8FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Dinner5,                     new Color(rgba: 0xEFEBE9FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.ForestSunset0,               new Color(rgba: 0x1B5E20FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ForestSunset1,               new Color(rgba: 0x2E7D32FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ForestSunset2,               new Color(rgba: 0x4CAF50FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ForestSunset3,               new Color(rgba: 0x81C784FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ForestSunset4,               new Color(rgba: 0xFFD54FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.ForestSunset5,               new Color(rgba: 0xFFC107FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Green0,                      new Color(rgba: 0x1B5E20FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Green1,                      new Color(rgba: 0x2E7D32FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Green2,                      new Color(rgba: 0x388E3CFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Green3,                      new Color(rgba: 0x43A047FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Green4,                      new Color(rgba: 0x4CAF50FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Green5,                      new Color(rgba: 0x81C784FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Heatwave0,                   new Color(rgba: 0x2E1A47FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Heatwave1,                   new Color(rgba: 0x4B0082FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Heatwave2,                   new Color(rgba: 0x800080FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Heatwave3,                   new Color(rgba: 0xFF005AFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Heatwave4,                   new Color(rgba: 0xFF4500FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Heatwave5,                   new Color(rgba: 0xFF8C00FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Icy0,                        new Color(rgba: 0x01579BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Icy1,                        new Color(rgba: 0x4A148CFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Icy2,                        new Color(rgba: 0x00B0FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Icy3,                        new Color(rgba: 0x7B1FA2FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Icy4,                        new Color(rgba: 0x40C4FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Icy5,                        new Color(rgba: 0xAA00FFFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Magenta0,                    new Color(rgba: 0x880E4FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Magenta1,                    new Color(rgba: 0xAD1457FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Magenta2,                    new Color(rgba: 0xC2185BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Magenta3,                    new Color(rgba: 0xD81B60FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Magenta4,                    new Color(rgba: 0xE91E63FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Magenta5,                    new Color(rgba: 0xF06292FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Orange0,                     new Color(rgba: 0xFFA726FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Orange1,                     new Color(rgba: 0xFF9800FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Orange2,                     new Color(rgba: 0xFB8C00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Orange3,                     new Color(rgba: 0xF57C00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Orange4,                     new Color(rgba: 0xEF6C00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Orange5,                     new Color(rgba: 0xE65100FF) },

        { IServiceColorInterpolatorDefinition.ColorType.OrangePurple0,               new Color(rgba: 0x4A148CFF) },
        { IServiceColorInterpolatorDefinition.ColorType.OrangePurple1,               new Color(rgba: 0x7B1FA2FF) },
        { IServiceColorInterpolatorDefinition.ColorType.OrangePurple2,               new Color(rgba: 0x9C27B0FF) },
        { IServiceColorInterpolatorDefinition.ColorType.OrangePurple3,               new Color(rgba: 0xBA68C8FF) },
        { IServiceColorInterpolatorDefinition.ColorType.OrangePurple4,               new Color(rgba: 0xFFB300FF) },
        { IServiceColorInterpolatorDefinition.ColorType.OrangePurple5,               new Color(rgba: 0xFF8F00FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.PoweradeSlushie0,            new Color(rgba: 0x004775FF) },
        { IServiceColorInterpolatorDefinition.ColorType.PoweradeSlushie1,            new Color(rgba: 0x005B99FF) },
        { IServiceColorInterpolatorDefinition.ColorType.PoweradeSlushie2,            new Color(rgba: 0x0072CEFF) },
        { IServiceColorInterpolatorDefinition.ColorType.PoweradeSlushie3,            new Color(rgba: 0x10C7DDFF) },
        { IServiceColorInterpolatorDefinition.ColorType.PoweradeSlushie4,            new Color(rgba: 0x82E1EDFF) },
        { IServiceColorInterpolatorDefinition.ColorType.PoweradeSlushie5,            new Color(rgba: 0xCAF7FBFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Purple0,                     new Color(rgba: 0xAB47BCFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Purple1,                     new Color(rgba: 0x9C27B0FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Purple2,                     new Color(rgba: 0x8E24AAFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Purple3,                     new Color(rgba: 0x7B1FA2FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Purple4,                     new Color(rgba: 0x6A1B9AFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Purple5,                     new Color(rgba: 0x4A148CFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Red0,                        new Color(rgba: 0xB71C1CFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Red1,                        new Color(rgba: 0xC62828FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Red2,                        new Color(rgba: 0xD32F2FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Red3,                        new Color(rgba: 0xE53935FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Red4,                        new Color(rgba: 0xF44336FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Red5,                        new Color(rgba: 0xE57373FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.RedWhiteBlue0,               new Color(rgba: 0x1976D2FF) },
        { IServiceColorInterpolatorDefinition.ColorType.RedWhiteBlue1,               new Color(rgba: 0x2196F3FF) },
        { IServiceColorInterpolatorDefinition.ColorType.RedWhiteBlue2,               new Color(rgba: 0xEEEEEEFF) },
        { IServiceColorInterpolatorDefinition.ColorType.RedWhiteBlue3,               new Color(rgba: 0xFFFFFFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.RedWhiteBlue4,               new Color(rgba: 0xF44336FF) },
        { IServiceColorInterpolatorDefinition.ColorType.RedWhiteBlue5,               new Color(rgba: 0xD32F2FFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.ShowinSomeLove0,             new Color(rgba: 0x4A0000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ShowinSomeLove1,             new Color(rgba: 0x880E4FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.ShowinSomeLove2,             new Color(rgba: 0xC2185BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.ShowinSomeLove3,             new Color(rgba: 0xE91E63FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ShowinSomeLove4,             new Color(rgba: 0xF06292FF) },
        { IServiceColorInterpolatorDefinition.ColorType.ShowinSomeLove5,             new Color(rgba: 0xF8BBD0FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak5_0,  new Color(rgba: 0x002B00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak5_1,  new Color(rgba: 0x004D00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak5_2,  new Color(rgba: 0x008000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak5_3,  new Color(rgba: 0x00FF00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak5_4,  new Color(rgba: 0x32CD32FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak5_5,  new Color(rgba: 0xADFF2FFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak10_0, new Color(rgba: 0x8B3A00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak10_1, new Color(rgba: 0xBF5000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak10_2, new Color(rgba: 0xFF6600FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak10_3, new Color(rgba: 0xFF8533FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak10_4, new Color(rgba: 0xFFA366FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak10_5, new Color(rgba: 0xFFC299FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak15_0, new Color(rgba: 0x310D3DFF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak15_1, new Color(rgba: 0x511B6BFF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak15_2, new Color(rgba: 0x7A2E9DFF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak15_3, new Color(rgba: 0x9E46C8FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak15_4, new Color(rgba: 0xBD72E0FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak15_5, new Color(rgba: 0xD8A8EFFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak20_0, new Color(rgba: 0x543E00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak20_1, new Color(rgba: 0x8C6700FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak20_2, new Color(rgba: 0xC69200FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak20_3, new Color(rgba: 0xFFBC00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak20_4, new Color(rgba: 0xFFD740FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TeamFortress2KillStreak20_5, new Color(rgba: 0xFFECB3FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.TokeUp0,                     new Color(rgba: 0x1B311FFF) },
        { IServiceColorInterpolatorDefinition.ColorType.TokeUp1,                     new Color(rgba: 0x2D5A27FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TokeUp2,                     new Color(rgba: 0x3D7B3EFF) },
        { IServiceColorInterpolatorDefinition.ColorType.TokeUp3,                     new Color(rgba: 0x4CAF50FF) },
        { IServiceColorInterpolatorDefinition.ColorType.TokeUp4,                     new Color(rgba: 0x8BC34AFF) },
        { IServiceColorInterpolatorDefinition.ColorType.TokeUp5,                     new Color(rgba: 0xCDDC39FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Toxic0,                      new Color(rgba: 0x39FF14FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Toxic1,                      new Color(rgba: 0xFF00FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Toxic2,                      new Color(rgba: 0xCCFF00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Toxic3,                      new Color(rgba: 0xFF1493FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Toxic4,                      new Color(rgba: 0x00FF00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Toxic5,                      new Color(rgba: 0xFF69B4FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Transition0,                 new Color(rgba: 0x000000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Transition1,                 new Color(rgba: 0x000000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Transition2,                 new Color(rgba: 0x000000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Transition3,                 new Color(rgba: 0x000000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Transition4,                 new Color(rgba: 0x000000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Transition5,                 new Color(rgba: 0x000000FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Vaporwave0,                  new Color(rgba: 0x240B36FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Vaporwave1,                  new Color(rgba: 0x9C27B0FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Vaporwave2,                  new Color(rgba: 0xFF00FFFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Vaporwave3,                  new Color(rgba: 0xFF5E62FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Vaporwave4,                  new Color(rgba: 0xFF9966FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Vaporwave5,                  new Color(rgba: 0xFFD194FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Watermelon0,                 new Color(rgba: 0x1B5E20FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Watermelon1,                 new Color(rgba: 0x4CAF50FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Watermelon2,                 new Color(rgba: 0x81C784FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Watermelon3,                 new Color(rgba: 0xFF8A8AFF) },
        { IServiceColorInterpolatorDefinition.ColorType.Watermelon4,                 new Color(rgba: 0xFF5252FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Watermelon5,                 new Color(rgba: 0xFF1744FF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.White0,                      new Color(rgba: 0x212121FF) },
        { IServiceColorInterpolatorDefinition.ColorType.White1,                      new Color(rgba: 0x424242FF) },
        { IServiceColorInterpolatorDefinition.ColorType.White2,                      new Color(rgba: 0x757575FF) },
        { IServiceColorInterpolatorDefinition.ColorType.White3,                      new Color(rgba: 0x9E9E9EFF) },
        { IServiceColorInterpolatorDefinition.ColorType.White4,                      new Color(rgba: 0xBDBDBDFF) },
        { IServiceColorInterpolatorDefinition.ColorType.White5,                      new Color(rgba: 0xEEEEEEFF) },
        
        { IServiceColorInterpolatorDefinition.ColorType.Yellow0,                     new Color(rgba: 0xFF6F00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Yellow1,                     new Color(rgba: 0xFF8F00FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Yellow2,                     new Color(rgba: 0xFFA000FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Yellow3,                     new Color(rgba: 0xFFB300FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Yellow4,                     new Color(rgba: 0xFFC107FF) },
        { IServiceColorInterpolatorDefinition.ColorType.Yellow5,                     new Color(rgba: 0xFFD54FFF) },
    };
}