
namespace Overlay.Core.Services.Achievements;

internal enum ServiceAchievementTitleTrack :
    uint
{
    // Meta Achievements
    CheckedBank,
    CheckedUnlocks,
    ClearedName,
    ClearedTitle,
    CompletedBhopBonus,
    CompletedBhopMap,
    CustomizedAvatar,
    CustomizedBadge,
    CustomizedName,
    CustomizedTitle,
    LinkedSteam,
    MessagesSent,
    MinutesWatched,
    PlayedDemoman,
    PlayedEngineer,
    PlayedHeavy,
    PlayedMedic,
    PlayedPyro,
    PlayedScout,
    PlayedSniper,
    PlayedSoldier,
    PlayedSpy,
    PreviewedUnlocks,
    QuestionsAsked,
    RockPaperScissorLose3InARow,
    RockPaperScissorLosses,
    RockPaperScissorMatchesPlayed,
    RockPaperScissorPapers,
    RockPaperScissorRocks,
    RockPaperScissorScissors,
    RockPaperScissorTie3InARow,
    RockPaperScissorTies,
    RockPaperScissorWin3InARow,
    RockPaperScissorWins,
    Rolled1,
    Rolled42,
    Rolled67,
    Rolled69,
    Rolled100,
    Rolls,
    RollsMaximum,
    RollsMinimum,
    SmoothDaggerDeaths,
    SmoothDaggerDominatedBys,
    SmoothDaggerDominations,
    SmoothDaggerKills,
    SmoothDaggerRevenges,
    TimesViewed,
    
    // Non-Meta Achievements
    Rolled240,
    Rolled256,
    Rolled420,
    Rolled720,
    Rolled1080,
    Rolled1337,
    Rolled3840,
    Rolled100000,
    TitlesUnlocked,
    TracksCompleted,
}