
using Overlay.Core.Services.Achievements;

namespace Overlay.Core.Contents.Mappings;

internal static class MappingTitleNames
{
    internal static ServiceAchievementTitle? GetTitleByTitleName(
        string titleName
    )
    {
        return titleName switch
        {
            // Meta Achievements
            "interesting"                      => ServiceAchievementTitle.CheckedBank_1,
            "unlocked"                         => ServiceAchievementTitle.CheckedUnlocks_1,
            "unnamed"                          => ServiceAchievementTitle.ClearedName_1,
            "no title"                         => ServiceAchievementTitle.ClearedTitle_1,
            "bonus"                            => ServiceAchievementTitle.CompletedBhopBonus_1,
            "bunny hopper"                     => ServiceAchievementTitle.CompletedBhopMap_1,
            "custom built"                     => ServiceAchievementTitle.CustomizedAvatar_1,
            "papers, please"                   => ServiceAchievementTitle.CustomizedBadge_1,
            "i have a name"                    => ServiceAchievementTitle.CustomizedName_1,
            "title & registration"             => ServiceAchievementTitle.CustomizedTitle_1,
            "steam linked"                     => ServiceAchievementTitle.LinkedSteam_1,
            "i talked"                         => ServiceAchievementTitle.MessagesSent_1,
            "i chatted"                        => ServiceAchievementTitle.MessagesSent_10,
            "i expressed"                      => ServiceAchievementTitle.MessagesSent_100,
            "i voiced"                         => ServiceAchievementTitle.MessagesSent_1000,
            "i proclaimed"                     => ServiceAchievementTitle.MessagesSent_10000,
            "i talked... a lot"                => ServiceAchievementTitle.MessagesSent_100000,
            "the spectator"                    => ServiceAchievementTitle.MinutesWatched_1,
            "the observer"                     => ServiceAchievementTitle.MinutesWatched_10,
            "the watcher"                      => ServiceAchievementTitle.MinutesWatched_100,
            "the regular"                      => ServiceAchievementTitle.MinutesWatched_1000,
            "the fixture"                      => ServiceAchievementTitle.MinutesWatched_10000,
            "the monument"                     => ServiceAchievementTitle.MinutesWatched_100000,
            "the demoman"                      => ServiceAchievementTitle.PlayedDemoman_1,
            "the engineer"                     => ServiceAchievementTitle.PlayedEngineer_1,
            "the heavy"                        => ServiceAchievementTitle.PlayedHeavy_1,
            "the medic"                        => ServiceAchievementTitle.PlayedMedic_1,
            "the pyro"                         => ServiceAchievementTitle.PlayedPyro_1,
            "the scout"                        => ServiceAchievementTitle.PlayedScout_1,
            "the sniper"                       => ServiceAchievementTitle.PlayedSniper_1,
            "the soldier"                      => ServiceAchievementTitle.PlayedSoldier_1,
            "the spy"                          => ServiceAchievementTitle.PlayedSpy_1,
            "eye candy"                        => ServiceAchievementTitle.PreviewedUnlocks_1,
            "just a little curious"            => ServiceAchievementTitle.QuestionsAsked_1,
            "asking the tough questions"       => ServiceAchievementTitle.QuestionsAsked_10,
            "questionable"                     => ServiceAchievementTitle.QuestionsAsked_100,
            "i'm done asking"                  => ServiceAchievementTitle.QuestionsAsked_1000,
            "unlucky"                          => ServiceAchievementTitle.RockPaperScissorLose3InARow_1,
            "i lost"                           => ServiceAchievementTitle.RockPaperScissorLosses_1,
            "skill issue"                      => ServiceAchievementTitle.RockPaperScissorLosses_10,
            ";_;"                              => ServiceAchievementTitle.RockPaperScissorLosses_100,
            "loser - beck"                     => ServiceAchievementTitle.RockPaperScissorLosses_1000,
            "challenger"                       => ServiceAchievementTitle.RockPaperScissorMatchesPlayed_1,
            "contender"                        => ServiceAchievementTitle.RockPaperScissorMatchesPlayed_10,
            "experienced"                      => ServiceAchievementTitle.RockPaperScissorMatchesPlayed_100,
            "veteran"                          => ServiceAchievementTitle.RockPaperScissorMatchesPlayed_1000,
            "traumatized"                      => ServiceAchievementTitle.RockPaperScissorMatchesPlayed_10000,
            "paper"                            => ServiceAchievementTitle.RockPaperScissorPapers_1,
            "flat hand"                        => ServiceAchievementTitle.RockPaperScissorPapers_10,
            "loose leaf"                       => ServiceAchievementTitle.RockPaperScissorPapers_100,
            "hole punched"                     => ServiceAchievementTitle.RockPaperScissorPapers_1000,
            "rock"                             => ServiceAchievementTitle.RockPaperScissorRocks_1,
            "fisticuffs"                       => ServiceAchievementTitle.RockPaperScissorRocks_10,
            "rock hard"                        => ServiceAchievementTitle.RockPaperScissorRocks_100,
            "stoned"                           => ServiceAchievementTitle.RockPaperScissorRocks_1000,
            "scissors"                         => ServiceAchievementTitle.RockPaperScissorScissors_1,
            "a cut above"                      => ServiceAchievementTitle.RockPaperScissorScissors_10,
            "sliced"                           => ServiceAchievementTitle.RockPaperScissorScissors_100,
            "straight edge"                    => ServiceAchievementTitle.RockPaperScissorScissors_1000,
            "average"                          => ServiceAchievementTitle.RockPaperScissorTie3InARow_1,
            "i tied"                           => ServiceAchievementTitle.RockPaperScissorTies_1,
            "mirrored"                         => ServiceAchievementTitle.RockPaperScissorTies_10,
            "all tied up"                      => ServiceAchievementTitle.RockPaperScissorTies_100,
            "deadlock"                         => ServiceAchievementTitle.RockPaperScissorTies_1000,
            "lucky"                            => ServiceAchievementTitle.RockPaperScissorWin3InARow_1,
            "i won"                            => ServiceAchievementTitle.RockPaperScissorWins_1,
            "hot hands"                        => ServiceAchievementTitle.RockPaperScissorWins_10,
            "^_^"                              => ServiceAchievementTitle.RockPaperScissorWins_100,
            "professional"                     => ServiceAchievementTitle.RockPaperScissorWins_1000,
            "1"                                => ServiceAchievementTitle.Rolled1_1,
            "answered"                         => ServiceAchievementTitle.Rolled42_1,
            "6-7"                              => ServiceAchievementTitle.Rolled67_1,
            "nice"                             => ServiceAchievementTitle.Rolled69_1,
            "a+"                               => ServiceAchievementTitle.Rolled100_1,
            "roll'd"                           => ServiceAchievementTitle.Rolls_1,
            "roller"                           => ServiceAchievementTitle.Rolls_10,
            "high roller"                      => ServiceAchievementTitle.Rolls_100,
            "diced"                            => ServiceAchievementTitle.Rolls_1000,
            "gambler"                          => ServiceAchievementTitle.Rolls_10000,
            "max"                              => ServiceAchievementTitle.RollsMaximum_1,
            "maximum"                          => ServiceAchievementTitle.RollsMaximum_1000,
            "min"                              => ServiceAchievementTitle.RollsMinimum_1,
            "minimum"                          => ServiceAchievementTitle.RollsMinimum_1000,
            "owned"                            => ServiceAchievementTitle.SmoothDaggerDominatedBys_1,
            "i'm done"                         => ServiceAchievementTitle.SmoothDaggerDominatedBys_10,
            "i died to smoothdagger"           => ServiceAchievementTitle.SmoothDaggerDeaths_1,
            "uninstalling"                     => ServiceAchievementTitle.SmoothDaggerDeaths_10,
            "i quit"                           => ServiceAchievementTitle.SmoothDaggerDeaths_100,
            "tf2 sucks"                        => ServiceAchievementTitle.SmoothDaggerDeaths_1000,
            "dominated"                        => ServiceAchievementTitle.SmoothDaggerDominations_1,
            "lol"                              => ServiceAchievementTitle.SmoothDaggerDominations_10,
            "first of many"                    => ServiceAchievementTitle.SmoothDaggerKills_1,
            "target practice"                  => ServiceAchievementTitle.SmoothDaggerKills_10,
            "kingslayer"                       => ServiceAchievementTitle.SmoothDaggerKills_100,
            "i killed smoothdagger"            => ServiceAchievementTitle.SmoothDaggerKills_1000,
            "a dish served cold"               => ServiceAchievementTitle.SmoothDaggerRevenges_1,
            "revenge"                          => ServiceAchievementTitle.SmoothDaggerRevenges_10,
            "new hire"                         => ServiceAchievementTitle.TimesViewed_1,
            "enjoying the view"                => ServiceAchievementTitle.TimesViewed_10,
            "lurkin' around"                   => ServiceAchievementTitle.TimesViewed_100,
            "gooner"                           => ServiceAchievementTitle.TimesViewed_1000,
            "cannot unsee"                     => ServiceAchievementTitle.TimesViewed_10000,
        
            // Non-Meta Achievements
            "240p"                             => ServiceAchievementTitle.Rolled240_1,
            "0xffffffff"                       => ServiceAchievementTitle.Rolled256_4,
            "#yoloswag420"                     => ServiceAchievementTitle.Rolled420_1,
            "720p"                             => ServiceAchievementTitle.Rolled720_1,
            "1080p"                            => ServiceAchievementTitle.Rolled1080_1,
            "i speak l33t"                     => ServiceAchievementTitle.Rolled1337_1,
            "ultra-wide 4k"                    => ServiceAchievementTitle.Rolled3840_1,
            "0.0001%"                          => ServiceAchievementTitle.Rolled100000_1,
            "i did it!"                        => ServiceAchievementTitle.TitlesUnlocked_1,
            "title grinder"                    => ServiceAchievementTitle.TitlesUnlocked_10,
            "the collector"                    => ServiceAchievementTitle.TitlesUnlocked_25,
            "legacy bearer"                    => ServiceAchievementTitle.TitlesUnlocked_50,
            "basically a pokemon trainer"      => ServiceAchievementTitle.TitlesUnlocked_75,
            "got'em all"                       => ServiceAchievementTitle.TitlesUnlocked_101,
            "tutorial completed"               => ServiceAchievementTitle.TracksCompleted_1,
            "on track"                         => ServiceAchievementTitle.TracksCompleted_5,
            "paving the way"                   => ServiceAchievementTitle.TracksCompleted_10,
            "trailblazer"                      => ServiceAchievementTitle.TracksCompleted_20,
            "completionist"                    => ServiceAchievementTitle.TracksCompleted_30,
            "god walking amongst mere mortals" => ServiceAchievementTitle.TracksCompleted_40,
            "i just work here"                 => ServiceAchievementTitle.TracksCompleted_48,
        
            // Only Given Achievements
            "dev"                              => ServiceAchievementTitle.Dev,
            _                                  => null,
        };
    }
}