using Godot;

namespace Overlay.Core.Contents.Effects.Backgrounds;

public enum EffectBackgroundAvatarShaderEffect : 
    uint
{
    Base              = 0,
    VaporGrid         = 1,
    SolarOrbits       = 2,
    MatrixStripes     = 3,
    EnergyScan        = 4,
    TopoLines         = 5,
    BioSparks         = 6,
    CellularArmor     = 7,
    LavaBubbles       = 8,
    DotMatrix         = 9,
    DataStream        = 10,
    ZebraSweep        = 11,
    LaserSweep        = 12,
    StaticGlitch      = 13,
    SilkThreads       = 14,
    TunnelStarfield   = 15,
    RollingMagma      = 16,
    CircuitFlow       = 17,
    RadarRing         = 18,
    HoneycombPulse    = 19,
    GlitchSlices      = 20,
    PlasmaDrift       = 21,
    RotatingCubes     = 22,
    OverdriveBars     = 23,
    FallingShards     = 24,
    BinaryRain        = 25,
    SpinningVortex    = 26,
    SonarPings        = 27,
    WindStreaks       = 28,
    HexShield         = 29,
    AtomicParticles   = 30,
    TrackingLines     = 31,
    NeuralFlash       = 32,
    OutwardRipples    = 33,
    PowerGrid         = 34,
    VerticalBitstream = 35,
    ScrollingVines    = 36,
    ElectricCracks    = 37,
    SwarmingNanites   = 38,
    MovingArcs        = 39,
    FractalZoom       = 40,
    MoireLines        = 41,
    VerticalDrift     = 42,
    ClockwiseSweep    = 43,
    PulseWave         = 44,
    SquareTiling      = 45,
    DiagonalRain      = 46,
    InterferenceBars  = 47,
    DiamondPulse      = 48,
    RgbShift          = 49
}