
namespace Overlay.Core.Contents.Effects.Backgrounds;

public enum EffectBackgroundAvatarShaderModel : 
    uint
{
    Human            = 0,
    Airplane         = 1,
    UFO              = 2,
    Spider           = 3,
    Dinosaur         = 4,
    HatsuneMiku      = 5,
    Robot            = 6,
    Tank             = 7,
    Gun              = 8,
    Pokeball         = 9,
    Jellyfish        = 10,
    XWing            = 11,
    TieFighter       = 12,
    Squid            = 13,
    Banana           = 14,
    Penis            = 15,
    Ghost            = 16,
    DeepSeaJellyfish = 17,
    Sentry           = 18,
    FryingPan        = 19,
    GLADoS           = 20,
    Potato           = 21,
    CompanionCube    = 22,
    Bread            = 23,
    StickyBomb       = 24,
    Katana           = 25,
    Star             = 26,
    Die              = 27,
    Rocket           = 28,
    Snowman          = 29,
    Asteroid         = 30,
    Octopus          = 31,
    Egg              = 32,
    Triangle         = 33,
    Tree             = 34,
    Cloud            = 35,
    Donut            = 36,
    Branch           = 37,
    Rook             = 38,
    Flask            = 39,
    Mushroom         = 40,
    Heart            = 41,
    Bone             = 42,
    DoubleHelix      = 43,
    SolarSystem      = 44,
    Gears            = 45,
    Brain            = 46,
    Hand             = 47,
    Dugtrio          = 48,
    Pikmin           = 49,
    Boobs            = 50,
}